name = "DiffusionMCMCTools"
uuid = "b3cd2978-1ca6-4f16-819e-f44b3a471639"
authors = ["Sebastiano Grazzi", "Frank van der Meulen", "Marcin Mider", "Moritz Schauer"]
version = "0.1.0"

[deps]
DiffusionDefinition = "c126fcb9-5a08-4fee-b75a-97eb446288b0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GuidedProposals = "2d53f948-c29b-4abe-a473-2cf2f1798516"
ObservationSchemes = "af94d80e-94fa-4c0b-866a-2d8bf15822bc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ObservationSchemes = "0.1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
